name: build-telegram

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 1) Clona o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2) Copiar o .env da raiz para dentro de bot/ (para o Makefile não falhar)
      - name: Copiar .env para dentro de bot/
        run: cp ./.env ./bot/.env

      # 3) Criar a pasta env/ e copiar .env para env/bot-telegram.env
      #    (para que o docker-compose-telegram.yml encontre o env_file)
      - name: Preparar arquivo de ambiente para o Compose
        run: |
          mkdir -p env
          cp ./.env ./env/bot-telegram.env

      # 4) Instalar Cosign (só fora de PR)
      - name: Instalar Cosign (só fora de PR)
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      # 5) Fazer login no registry (só fora de PR)
      - name: Fazer login no registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6) Build das imagens usando o docker-compose-telegram.yml
      - name: Build das imagens (docker-compose-telegram.yml)
        run: |
          docker compose -f docker-compose-telegram.yml build

      # 7) Push das imagens (só fora de PR)
      - name: Publicar imagens no registry (docker-compose-telegram.yml)
        if: github.event_name != 'pull_request'
        run: |
          docker compose -f docker-compose-telegram.yml push

      # 8) Assinar as imagens com Cosign (só fora de PR)
      - name: Assinar imagens publicadas com Cosign
        if: github.event_name != 'pull_request'
        env:
          # Atenção: ajuste esta tag exatamente como você definiu em docker-compose-telegram.yml
          # Exemplo: se no YAML você colocou
          #   services:
          #     bot:
          #       image: ghcr.io/${{ github.repository }}:bot-${{ github.sha }}
          #
          # então mantenha essa mesma string aqui:
          IMAGE_TAG: ghcr.io/${{ github.repository }}:bot-${{ github.sha }}
        run: |
          # Em vez de tentar inspecionar o digest, basta chamar o Cosign na TAG
          cosign sign --yes "$IMAGE_TAG"

          # Se tiver outros serviços (por ex. "worker"), repita:
          # IMAGE_TAG=ghcr.io/${{ github.repository }}:worker-${{ github.sha }}
          # cosign sign --yes "$IMAGE_TAG"
