name: build-telegram

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 1) Clonar o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2) Copiar o .env da raiz para dentro de bot/
      - name: Copiar .env para dentro de bot/
        run: cp ./.env ./bot/.env

      # 3) Criar a pasta env/ e copiar .env para env/bot-telegram.env
      - name: Preparar arquivo de ambiente para o Compose
        run: |
          mkdir -p env
          cp ./.env ./env/bot-telegram.env

      # 4) Instalar Cosign (só fora de PR)
      - name: Instalar Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20
        with:
          cosign-release: 'v2.2.4'

      # 5) Fazer login no GHCR (só fora de PR)
      - name: Fazer login no registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6) Build e Push das imagens
      - name: Build das imagens (docker-compose-telegram.yml)
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker compose -f docker-compose-telegram.yml build

      - name: Publicar imagens no registry (docker-compose-telegram.yml)
        if: github.event_name != 'pull_request'
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker compose -f docker-compose-telegram.yml push

      # 7) Assinar as imagens com Cosign (só fora de PR)
      - name: Assinar imagens publicadas com Cosign
        if: github.event_name != 'pull_request'
        env:
          # Este IMAGE_TAG deve combinar exatamente com o `image:` que você colocou no Compose acima.
          IMAGE_TAG: ghcr.io/${{ github.repository }}:bot-${{ github.sha }}
        run: |
          echo ">> Puxando a imagem para garantir que ela exista localmente"
          docker pull "$IMAGE_TAG"

          echo ">> Extraindo o digest que foi gerado pelo pull"
          DIGEST="$(docker image inspect "$IMAGE_TAG" --format='{{ index .RepoDigests 0 }}')"

          if [ -z "$DIGEST" ]; then
            echo "❌ Não foi possível extrair o digest da imagem (RepoDigests vazio)."
            exit 1
          fi

          echo ">> Digest encontrado: $DIGEST"
          echo ">> Iniciando assinatura com Cosign"
          cosign sign --yes "$DIGEST"

          echo "✔️ Imagem assinada com sucesso: $DIGEST"
